version: '3.6'
services:
  web:
    build: ServerAndClient/docker_main
    # command: 
    #   - sh -c "python manage.py makemigrations opc && python manage.py migrate && python manage.py runserver"
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.env
    depends_on:
      - dbserver

  dbserver:
    build: ServerAndClient/dbserver
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=frank 
      - POSTGRES_PASSWORD=frank 
      - POSTGRES_DB=opcuaDB
    ports:
      - 5432:5432
volumes:
  postgres_data: