version: '2.1'
services:
  web:
    build: ServerAndClient/docker_main
    depends_on:
      dbserver:
        condition: service_healthy
    # command: 
    #   - sh -c "python manage.py makemigrations opc && python manage.py migrate && python manage.py runserver"
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.env
    environment:
      - BASE_PATH=$PWD

  dbserver:
    build: ServerAndClient/dbserver
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=frank 
      - POSTGRES_PASSWORD=frank 
      - POSTGRES_DB=opcuaDB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U frank -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    # the mapping is not necessary 
    # ports:
    #   - 55432:5432
volumes:
  postgres_data:
