# Generated by Django 3.0a1 on 2019-10-07 16:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dienstleistungen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicenummer', models.PositiveSmallIntegerField(default=0, unique=True)),
                ('serviceName', models.CharField(max_length=30, unique=True)),
                ('serviceBeschreibung', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntProdukt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intProduknummer', models.PositiveSmallIntegerField(default=0, unique=True)),
                ('produktName', models.CharField(max_length=30)),
                ('produktBeschreibung', models.TextField(max_length=200, null=True)),
                ('dieIntProd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='opc_ua.Dienstleistungen')),
            ],
        ),
        migrations.CreateModel(
            name='Kunden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kundennummer', models.PositiveSmallIntegerField(default=0, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('Telefonnummer', models.PositiveIntegerField(null=True)),
                ('ort', models.CharField(max_length=30)),
                ('plz', models.PositiveIntegerField(null=True)),
                ('strasse', models.CharField(max_length=30)),
                ('hausnummer', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegOpcUaServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regServerID', models.PositiveSmallIntegerField(default=0, unique=True)),
                ('servername', models.CharField(max_length=30, unique=True)),
                ('ort', models.CharField(max_length=30)),
                ('portnummer', models.PositiveIntegerField(null=True)),
                ('registrieungsstatus', models.CharField(choices=[('Starten', 'Starten'), ('Gestartet', 'Gestartet'), ('Stoppen', 'Stoppen'), ('Gestoppt', 'Gestoppt')], default='Gestoppt', max_length=20)),
                ('regestrierungsZeit', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VirtuelleOpcUaServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtuellServerID', models.PositiveSmallIntegerField(default=0, unique=True)),
                ('servername', models.CharField(max_length=30, unique=True)),
                ('ort', models.CharField(max_length=30)),
                ('portnummer', models.PositiveIntegerField(null=True)),
                ('serverstatus', models.CharField(choices=[('Starten', 'Starten'), ('Gestartet', 'Gestartet'), ('Stoppen', 'Stoppen'), ('Gestoppt', 'Gestoppt')], default='Gestoppt', max_length=20)),
                ('autoStart', models.BooleanField(default=False)),
                ('anzahlOffeneAuftraege', models.PositiveIntegerField(null=True)),
                ('anzahlAbgesAuftraege', models.PositiveIntegerField(null=True)),
                ('AktuelleAuftraegsNr', models.PositiveIntegerField(null=True)),
                ('startZeit', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProduktionsAuftrag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auftragsnummer', models.PositiveSmallIntegerField(default=0, unique=True)),
                ('aktuellerSchritt', models.PositiveIntegerField(null=True)),
                ('Anzahlschritte', models.PositiveIntegerField(null=True)),
                ('Fortschritt', models.PositiveIntegerField(null=True)),
                ('auftragsstatus', models.CharField(choices=[('Geplant', 'Geplant'), ('InBearbeitung', 'InBearbeitung'), ('Gestoppt', 'Gestoppt'), ('Abgeschossen', 'Abgeschossen')], default='Geplant', max_length=20)),
                ('LetzteAktuallisierung', models.DateTimeField(null=True)),
                ('intProdukt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='opc_ua.IntProdukt')),
                ('kundennummer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='opc_ua.Kunden')),
            ],
        ),
        migrations.CreateModel(
            name='DienstVirtOpcUaServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dieVirtOpcUaID', models.PositiveSmallIntegerField(default=0, unique=True)),
                ('running_simulation', models.DurationField(default=datetime.timedelta(seconds=120))),
                ('virtserver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='opc_ua.VirtuelleOpcUaServer')),
            ],
        ),
        migrations.CreateModel(
            name='DienstOpcUaServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dieOpcUaID', models.PositiveSmallIntegerField(default=0, unique=True)),
                ('regServer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='opc_ua.RegOpcUaServer')),
            ],
        ),
        migrations.AddField(
            model_name='dienstleistungen',
            name='dieOpcUa',
            field=models.ManyToManyField(to='opc_ua.DienstOpcUaServer'),
        ),
        migrations.AddField(
            model_name='dienstleistungen',
            name='dieVirtOpcUa',
            field=models.ManyToManyField(to='opc_ua.DienstVirtOpcUaServer'),
        ),
        migrations.CreateModel(
            name='DieIntProdukt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dieIntProduktID', models.PositiveSmallIntegerField(default=0, unique=True)),
                ('anzahlService', models.PositiveIntegerField(null=True)),
                ('sequenz', models.PositiveIntegerField(null=True)),
                ('servicenummer', models.ManyToManyField(to='opc_ua.Dienstleistungen')),
            ],
        ),
    ]
